# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aggiungi libro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newprofile(object):
    def setupUi(self, newprofile):
        newprofile.setObjectName("newprofile")
        newprofile.resize(875, 795)
        font = QtGui.QFont()
        font.setPointSize(12)
        newprofile.setFont(font)
        newprofile.setStyleSheet("background-color:#41383C;")
        self.centralwidget = QtWidgets.QWidget(newprofile)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(10)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, 30)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Avatar = QtWidgets.QLabel(self.frame)
        self.Avatar.setMinimumSize(QtCore.QSize(300, 200))
        self.Avatar.setMaximumSize(QtCore.QSize(300, 200))
        self.Avatar.setStyleSheet("background-color:white;")
        self.Avatar.setText("")
        self.Avatar.setScaledContents(False)
        self.Avatar.setObjectName("Avatar")
        self.horizontalLayout_2.addWidget(self.Avatar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.caricafotoprofilo = QtWidgets.QPushButton(self.frame)
        self.caricafotoprofilo.setMinimumSize(QtCore.QSize(200, 0))
        self.caricafotoprofilo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.caricafotoprofilo.setAutoFillBackground(False)
        self.caricafotoprofilo.setStyleSheet("border-radius:2px;background-color:white;border:1px solid grey;")
        self.caricafotoprofilo.setObjectName("caricafotoprofilo")
        self.horizontalLayout_2.addWidget(self.caricafotoprofilo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Edit_titolo = QtWidgets.QLineEdit(self.frame)
        self.Edit_titolo.setMinimumSize(QtCore.QSize(300, 0))
        self.Edit_titolo.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Italic")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Edit_titolo.setFont(font)
        self.Edit_titolo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Edit_titolo.setAutoFillBackground(False)
        self.Edit_titolo.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.Edit_titolo.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_titolo.setObjectName("Edit_titolo")
        self.verticalLayout.addWidget(self.Edit_titolo)
        self.Edit_cognome = QtWidgets.QLineEdit(self.frame)
        self.Edit_cognome.setMinimumSize(QtCore.QSize(300, 0))
        self.Edit_cognome.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Italic")
        font.setPointSize(12)
        font.setKerning(False)
        self.Edit_cognome.setFont(font)
        self.Edit_cognome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Edit_cognome.setAutoFillBackground(False)
        self.Edit_cognome.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.Edit_cognome.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_cognome.setObjectName("Edit_cognome")
        self.verticalLayout.addWidget(self.Edit_cognome)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.conferma = QtWidgets.QPushButton(self.frame)
        self.conferma.setMinimumSize(QtCore.QSize(100, 20))
        self.conferma.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.conferma.setFont(font)
        self.conferma.setStyleSheet("border-radius:2px;background-color:white;border:1px solid grey;")
        self.conferma.setObjectName("conferma")
        self.horizontalLayout.addWidget(self.conferma)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.indietro = QtWidgets.QPushButton(self.centralwidget)
        self.indietro.setMinimumSize(QtCore.QSize(100, 20))
        self.indietro.setMaximumSize(QtCore.QSize(100, 20))
        self.indietro.setObjectName("indietro")
        self.gridLayout.addWidget(self.indietro, 6, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        newprofile.setCentralWidget(self.centralwidget)
        self.actionIndietro = QtWidgets.QAction(newprofile)
        self.actionIndietro.setObjectName("actionIndietro")
        self.actionIndietro_2 = QtWidgets.QAction(newprofile)
        self.actionIndietro_2.setObjectName("actionIndietro_2")
    
        self.caricafotoprofilo.setText("carica foto profilo")
        self.Edit_titolo.setPlaceholderText("Titolo")
        self.Edit_cognome.setPlaceholderText("autore")
        self.conferma.setText("conferma")
        self.indietro.setText("← indietro")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newprofile = QtWidgets.QMainWindow()
    ui = Ui_newprofile()
    ui.setupUi(newprofile)
    newprofile.show()
    sys.exit(app.exec_())
