# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aggiungi maestre.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newprofile(object):
    def setupUi(self, newprofile):
        newprofile.setObjectName("newprofile")
        newprofile.resize(875, 795)
        font = QtGui.QFont()
        font.setPointSize(12)
        newprofile.setFont(font)
        newprofile.setStyleSheet("background-color:#41383C;")
        self.centralwidget = QtWidgets.QWidget(newprofile)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(10)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, 30)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Avatar = QtWidgets.QLabel(self.frame)
        self.Avatar.setMinimumSize(QtCore.QSize(300, 200))
        self.Avatar.setMaximumSize(QtCore.QSize(300, 200))
        self.Avatar.setStyleSheet("")
        self.Avatar.setText("")
        self.Avatar.setPixmap(QtGui.QPixmap("../Icons/maestra.png"))
        self.Avatar.setScaledContents(True)
        self.Avatar.setObjectName("Avatar")
        self.horizontalLayout_2.addWidget(self.Avatar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Edit_nome = QtWidgets.QLineEdit(self.frame)
        self.Edit_nome.setMinimumSize(QtCore.QSize(300, 0))
        self.Edit_nome.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Italic")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Edit_nome.setFont(font)
        self.Edit_nome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Edit_nome.setAutoFillBackground(False)
        self.Edit_nome.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.Edit_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_nome.setObjectName("Edit_nome")
        self.verticalLayout.addWidget(self.Edit_nome)
        self.Edit_cognome = QtWidgets.QLineEdit(self.frame)
        self.Edit_cognome.setMinimumSize(QtCore.QSize(300, 0))
        self.Edit_cognome.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Italic")
        font.setPointSize(12)
        font.setKerning(False)
        self.Edit_cognome.setFont(font)
        self.Edit_cognome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Edit_cognome.setAutoFillBackground(False)
        self.Edit_cognome.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.Edit_cognome.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_cognome.setObjectName("Edit_cognome")
        self.verticalLayout.addWidget(self.Edit_cognome)
        self.Edit_Password = QtWidgets.QLineEdit(self.frame)
        self.Edit_Password.setMinimumSize(QtCore.QSize(300, 0))
        self.Edit_Password.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Italic")
        font.setPointSize(12)
        font.setKerning(False)
        self.Edit_Password.setFont(font)
        self.Edit_Password.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Edit_Password.setAutoFillBackground(False)
        self.Edit_Password.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.Edit_Password.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_Password.setObjectName("Edit_Password")
        self.verticalLayout.addWidget(self.Edit_Password)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setMinimumSize(QtCore.QSize(300, 23))
        self.checkBox.setMaximumSize(QtCore.QSize(300, 23))
        self.checkBox.setStyleSheet("border-radius:5px;border:1px solid grey;background-color:white;")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.conferma = QtWidgets.QPushButton(self.frame)
        self.conferma.setMinimumSize(QtCore.QSize(100, 20))
        self.conferma.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.conferma.setFont(font)
        self.conferma.setStyleSheet("border-radius:2px;background-color:white;border:1px solid grey;")
        self.conferma.setObjectName("conferma")
        if(modifica == True):
            self.conferma.clicked.connect(self.modifica_maestra)
        else:
            self.conferma.clicked.connect(self.inserimento_nuovo_maestra)
        self.horizontalLayout.addWidget(self.conferma)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.indietro = QtWidgets.QPushButton(self.centralwidget)
        self.indietro.setMinimumSize(QtCore.QSize(100, 20))
        self.indietro.setMaximumSize(QtCore.QSize(100, 20))
        self.indietro.setObjectName("indietro")
        self.gridLayout.addWidget(self.indietro, 6, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)

        self.Edit_nome.setPlaceholderText("nome")
        self.Edit_cognome.setPlaceholderText("cognome")
        self.Edit_Password.setPlaceholderText("Password")
        self.checkBox.setText("Amministratore")
        self.conferma.setText("conferma")
        self.indietro.setText("← indietro")

        if(modifica == True):
            self.Carica_items_maestre()

        self.centralWidget().setLayout(self.gridLayout)
        self.show()

    def inserimento_nuovo_maestra(self):
        nome = self.Edit_nome.text()
        cognome = self.Edit_cognome.text()
        password = self.Edit_Password.text()
        amministratore = self.checkBox.checkState()
        cndb.insert_admin(nome,cognome,password,amministratore)

    def Carica_items_maestre(self):
        global id_Admin
        result = cndb.filter_ID_to_maestre(id_Admin)
        self.Edit_nome.setText(result[0][0])
        self.Edit_cognome.setText(result[1][0])
        self.Edit_Password.setText(result[2][0])
        self.checkBox.setCheckState(result[3][0])


    def modifica_maestra(self,id_Maestra):
        nome = self.Edit_nome.text()
        cognome = self.Edit_cognome.text()
        password = self.Edit_Password.text()
        amministratore = self.checkBox.checkState()
        cndb.edit_admin(nome,cognome,password,amministratore,id_Admin)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newprofile = QtWidgets.QMainWindow()
    ui = Ui_newprofile()
    ui.setupUi(newprofile)
    newprofile.show()
    sys.exit(app.exec_())
