# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Info_Client.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info_Client(object):
    def setupUi(self, Info_Client):
        self.gridLayout = QtWidgets.QGridLayout(Info_Client)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Button_indietro = QtWidgets.QPushButton(Info_Client)
        self.Button_indietro.setMinimumSize(QtCore.QSize(230, 30))
        self.Button_indietro.setStyleSheet("background-color:rgb(240,0,0)")
        self.Button_indietro.setObjectName("Button_indietro")
        self.horizontalLayout_4.addWidget(self.Button_indietro)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(Info_Client)
        self.label_5.setMinimumSize(QtCore.QSize(430, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.listWidget_libri = QtWidgets.QListWidget(Info_Client)
        self.listWidget_libri.setMinimumSize(QtCore.QSize(530, 390))
        self.listWidget_libri.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_libri.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.listWidget_libri.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_libri.setObjectName("listWidget_libri")
        self.verticalLayout_5.addWidget(self.listWidget_libri)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.Button_consegna = QtWidgets.QPushButton(Info_Client)
        self.Button_consegna.setMinimumSize(QtCore.QSize(365, 120))
        self.Button_consegna.setStyleSheet("background-color:rgb(0, 234, 15);")
        self.Button_consegna.setObjectName("Button_consegna")
        self.verticalLayout.addWidget(self.Button_consegna)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.Button_prendi = QtWidgets.QPushButton(Info_Client)
        self.Button_prendi.setMinimumSize(QtCore.QSize(365, 120))
        self.Button_prendi.setStyleSheet("background-color:rgb(0, 159, 195)")
        self.Button_prendi.setObjectName("Button_prendi")
        self.verticalLayout.addWidget(self.Button_prendi)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Info_Client)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Info_Client)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Img_avatar = QtWidgets.QLabel(Info_Client)
        self.Img_avatar.setMinimumSize(QtCore.QSize(240, 240))
        self.Img_avatar.setMaximumSize(QtCore.QSize(240, 240))
        self.Img_avatar.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Img_avatar.setAutoFillBackground(False)
        self.Img_avatar.setStyleSheet("Background-color:rgb(255, 255, 255);")
        self.Img_avatar.setText("")
        self.Img_avatar.setScaledContents(True)
        self.Img_avatar.setObjectName("Img_avatar")
        self.horizontalLayout_2.addWidget(self.Img_avatar)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nome = QtWidgets.QLabel(Info_Client)
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout_2.addWidget(self.label_nome)
        self.label_cognome = QtWidgets.QLabel(Info_Client)
        self.label_cognome.setObjectName("label_cognome")
        self.verticalLayout_2.addWidget(self.label_cognome)
        self.label_classe = QtWidgets.QLabel(Info_Client)
        self.label_classe.setObjectName("label_classe")
        self.verticalLayout_2.addWidget(self.label_classe)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.Img_cover = QtWidgets.QLabel(Info_Client)
        self.Img_cover.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Img_cover.setStyleSheet("background-color:#FFFFFF;")
        self.Img_cover.setText("")
        self.Img_cover.setObjectName("Img_cover")
        self.horizontalLayout_2.addWidget(self.Img_cover)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.Button_indietro.setText("Indietro")
        self.label_5.setText("Libri Inpossesso")
        self.Button_consegna.setText("Restituisci")
        self.Button_prendi.setText("Prendi in prestito")
        self.label_nome.setText("Nome:")
        self.label_cognome.setText( "Cognome:")
        self.label_classe.setText("Classe:")

        QtCore.QMetaObject.connectSlotsByName(Info_Client)

   

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Info_Client = QtWidgets.QDialog()
    ui = Ui_Info_Client()
    ui.setupUi(Info_Client)
    Info_Client.show()
    sys.exit(app.exec_())
