# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\prestito.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bookcard(object):
    def setupUi(self, bookcard):
        bookcard.setObjectName("bookcard")
        bookcard.resize(914, 753)
        bookcard.setStyleSheet("background-color:#6e6868;")
        global Root, id_libro
        self.centralwidget = QtWidgets.QWidget(bookcard)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 5, 1, 1)
        self.indietro = QtWidgets.QPushButton(self.centralwidget)
        self.indietro.setObjectName("indietro")
        self.indietro.clicked.connect(self.Dati_Bimbo)
        self.gridLayout.addWidget(self.indietro, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(700, 700))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(10)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Img_cover = QtWidgets.QLabel(self.frame)
        self.Img_cover.setMinimumSize(QtCore.QSize(346, 400))
        self.Img_cover.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Img_cover.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Img_cover.setStyleSheet("Background-color:rgb(255, 255, 255)")
        self.Img_cover.setFrameShape(QtWidgets.QFrame.Box)
        self.Img_cover.setLineWidth(2)
        self.Img_cover.setText("")
        self.Img_cover.setScaledContents(True)
        self.Img_cover.setObjectName("Img_cover")
        self.verticalLayout.addWidget(self.Img_cover)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.restituisci = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.restituisci.setFont(font)
        self.restituisci.setStyleSheet("border-radius:15px;border:1px solid white;background-color:rgb(85, 255, 255);")
        self.restituisci.setObjectName("restituisci")
        self.verticalLayout_2.addWidget(self.restituisci)
        self.restituisci.clicked.connect(self.restituisci_libro)
        self.prendi = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.prendi.setFont(font)
        self.prendi.setStyleSheet("border-radius:15px;border:1px solid white;background-color:green;")
        self.prendi.setObjectName("prendi")
        self.prendi.clicked.connect(self.prendi_libro)
        self.verticalLayout_2.addWidget(self.prendi)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 3, 3, 1, 1)

        result = cndb.show_book_by_ID_all(id_libro)
        data = tuple(result.fetchall())
        cndb.close_db()
        self.label_3.setText("Titolo: "+data[1][0])
        self.label_4.setText("Autore: "+data[2][0])
        self.label_5.setText("Genere: "+data[3][0])
        self.Img_cover.setPixmap(QtGui.QPixmap(Root+data[4][0]))

        self.indietro.setText("← Indietro")
        self.label.setText("copertina del libro")
        self.label_2.setText("Informazini sul libro")
        self.pushButton.setText("Restituisci")
        self.prendi.setText("Prendi")
    
    def prendi_libro(self):
        global id_bimbo, id_libro
        cndb.add_logs_book(id_bimbo,id_libro)
    
    def restituisci_libro(self):
        global id_bimbo, id_libro
        cndb.romve_logs_book(id_bimbo,id_libro)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bookcard = QtWidgets.QMainWindow()
    ui = Ui_bookcard()
    ui.setupUi(bookcard)
    bookcard.show()
    sys.exit(app.exec_())
